---
- hosts: all

  collections:
    - ansible.posix

  handlers:
    - name: restart_docker
      systemd:
        name: docker
        daemon_reload: yes
        state: restarted

  tasks:
    - apt:
        package:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "gnupg-agent",
            "software-properties-common",
            "ceph-common",
          ]
        state: present

    - apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present

    - apt:
        package: ["docker-ce", "docker-ce-cli", "containerd.io"]
        state: present

    - file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - copy:
        content: |2+
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json
      notify: restart_docker

    - systemd:
        name: docker
        enabled: yes

    - ansible.posix.sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
